# fastlane/Fastfile
default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    cocoapods

    build_app(
      scheme: "mobile",
      configuration: "Release",
      export_method: "app-store",
      include_bitcode: false,
      include_symbols: true,
      clean: true,
      xcargs: "RCT_NO_LAUNCH_PACKAGER=1"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false,
      uses_non_exempt_encryption: false
    )
  end
end
