# fastlane/Fastfile
default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Ensure Xcode tools are selected and gems installed
    cocoapods

    build_app(
      scheme: "mobile",
      configuration: "Release",          # garante build Release
      export_method: "app-store",
      include_bitcode: false,
      include_symbols: true,
      clean: true,
      xcargs: "RCT_NO_LAUNCH_PACKAGER=1" # evita tentar abrir o Metro
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      submit_for_beta_review: false,
      distribute_external: false
    )
  end
end
